/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.SignBadResponse;
import io.swagger.model.SigninResponse;
import io.swagger.model.User;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-21T06:59:45.566Z")

@Api(value = "signin", description = "the signin API")
public interface SigninApi {

    @ApiOperation(value = "사용자 인증", nickname = "userCertification", notes = "사용자 인증", response = SigninResponse.class, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = SigninResponse.class),
        @ApiResponse(code = 400, message = "Invalid input", response = SignBadResponse.class),
        @ApiResponse(code = 401, message = "Invalid input", response = SignBadResponse.class) })
    @RequestMapping(value = "/signin",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<SigninResponse> userCertification(@ApiParam(value = "" ,required=true )  @Valid @RequestBody User email);

}
